---
title: "analysis1"
author: "Miklos Bognar"
date: "2023-01-13"
output: html_document
---

# Source to raw
## Load packages for this section
```{r message=F}
library(tidyverse)
library(papaja)
library(lme4)
library(lmerTest)
```

## Loading data
```{r}
source_data = read.csv("data/pilot_data.csv")
```

## Demographic analysis
---------------------------

## Prepare for sequential analysis
### Use only response data
```{r}
raw_data = source_data %>% 
  filter(task == "response")
```

### Check all the conditions with mean RT
```{r}
raw_data %>% 
  group_by(congruency) %>% 
  summarize(N = n(),
            mean_rt = mean(as.numeric(rt), na.rm = T)) %>% 
  ungroup()
```

### Create a numeric id from 
```{r}
raw_data = raw_data %>%
  group_by(participant_id) %>% 
  mutate(id = cur_group_id()) %>% 
  ungroup()
```

### Create previous trial data
```{r}
raw_data = raw_data %>% 
  arrange(participant_id, as.numeric(trial_index)) %>% 
  mutate(previous_rt = lag(rt),
         previous_congruency = lag(congruency),
         previous_correct = lag(correct))
  
```

### Create rt and accuracy data
```{r}
raw_rt = raw_data %>% 
  filter(correct == "true",
         previous_correct == "true",
         previous_rt > 0)
```

```{r}
raw_accuracy = raw_data
```

### Check cse without outlier detection
```{r}
cse_data = raw_rt %>% 
  group_by(congruency, previous_congruency) %>% 
  summarize(N = n(),
            mean_rt = mean(as.numeric(rt), na.rm = T),
            sd_rt = sd(rt, na.rm = T),
            se_rt = sd_rt/sqrt(N))
```
```{r}
cse_plot = cse_data %>% 
  ggplot()+
  aes(x=factor(previous_congruency, level=c("no_conflict","low_conflict")), y=mean_rt, color=congruency, group=congruency)+
  geom_point(size=2)+
  geom_path(size=1)+
  geom_errorbar(size=1,aes(ymin=mean_rt-se_rt,
                    ymax=mean_rt+se_rt,
                    width=.2))+
  papaja::theme_apa()+
  labs(x="Previous Congruency",
       y= "Reaction time",
       color="Current Congruency",
       title="Pilot CSE plot")



cse_plot
```

```{r}
mymodel = lmer(as.numeric(rt) ~ congruency * previous_congruency + (1|id), data=raw_rt)
summary(mymodel)
anova(mymodel)
```


